### ISSUE TITLE
关于论文的算法配图

### ISSUE THREAD

**Issue by ljhOfGithub** [liupei101/GraphLSurv#2]
![image](https://github.com/liupei101/GraphLSurv/assets/42089575/a41909c4-9554-4592-8625-b98f1412f663)
![image](https://github.com/liupei101/GraphLSurv/assets/42089575/384dcb20-bb64-4c95-a274-ae8c86523db2)
您好！感谢您的贡献！我发现您在论文中的算法配图的排版有点问题，好像换行和空格出现了小问题，您可以修改一下格式吗？或者您简单阐述P矩阵是怎么得到的，因为上文没有提及P矩阵的获取方式，非常感谢！

**Comment by liupei101** [comment]
您好，谢谢关注！

我们上传了一份最新的版本（[地址](https://github.com/liupei101/GraphLSurv/blob/main/docs/2023-CMPB-GraphLSurv-Draft.pdf)）。大概是期刊那边正式出版时出现了排版问题。

矩阵 P 是原特征矩阵 X 经过矩阵 T 投影后的新特征矩阵（见最新版本第五页左栏最后一段描述）。这个新的特征矩阵 P 用来计算Patch与Patch之间的cosine距离，得到矩阵A_L。
